config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ask', to: 'questions#ask', as: 'ask'
  get 'answer', to: 'questions#answer', as: 'answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @ask = params[:question]
    if @ask == "I am going to work"
      @answer = "Great!"
    elsif @ask.last == "?"
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Stupid Coaching</h1>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<p>
  <%=  @ask %><br>
  — You
<br><br>
  <%=  @answer %><br>
  — Your coach
</p>
<br>
<p class=link><%= link_to "Ask a new question", ask_path %></p>

app/views/questions/ask.html.erb
<p>Ask your coach something:</p>
<form action="answer">
  <input type="text" name="question" class="input-coach">
  <input type="submit" value="Ask" class="btn">
</form>